name: Elixir CI (changed directories)

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "elixir/**"

permissions:
  contents: read

jobs:
  diff:
    name: Determine directories to be tested
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-matrix.outputs.dirs }}
    steps:
    - uses: actions/checkout@v7
    - id: set-matrix
      run: |
        DIRS_JSON='[]'
        if [ "${{ github.event_name }}" = "push" ]; then
          DIRS_JSON=$(find elixir/ -maxdepth 1 -mindepth 1 -type d | sed -E 's|^elixir/([^\]+)|"\1"|' | sort -u | jq -sc .)
        else
          git fetch origin main
          DIRS_JSON=$(git diff --name-only origin/main @ -- elixir/ | sed -E 's|^elixir/([^/]+)/.+|"\1"|' | sort -u | jq -sc .)
        fi
        echo "dirs=$DIRS_JSON" >> "$GITHUB_OUTPUT"

  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: diff

    strategy:
      matrix:
        exercise: ${{ fromJSON(needs.diff.outputs.dirs) }}

    steps:
    - uses: actions/checkout@v7
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.20.4' # [Required] Define the Elixir version
        otp-version: '29.0'      # [Required] Define the Erlang/OTP version
    - name: Restore dependencies cache
      uses: actions/cache@v6
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Run tests
      run: |
        cd elixir/${{ matrix.exercise }}/
        mix deps.get
        mix test --include pending
